#!/usr/bin/env python3
"""Build public/i18n/deep-en-final.js + src/lib/i18n-phrases.ts from a static map."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# TR → EN. Proper nouns kept. Gameplay meaning preserved.
MAP: dict[str, str] = {
    # TC SIM lifetime / catalog / systems
    "Yetişkin çocuğunla yeni bir dönem": "A new chapter with your adult child",
    "Eğitim, iş ve bağımsız yaşam artık onun kararları. Desteğinin sınırlarını birlikte konuşabilirsiniz.": "School, work and independent life are now their calls. You can still talk through the limits of your support.",
    "₺1.500 destek ver, kararını dinle": "Give ₺1,500 of support and hear their decision",
    "Kendi önerdiğin yönde ısrar et": "Push the path you proposed",
    "Kararına alan bırak": "Leave room for their decision",
    "Market Çalışanı": "Shop clerk",
    "Kurye": "Courier",
    "Ofis Asistanı": "Office assistant",
    "Teknik Servis Uzmanı": "Field technician",
    "Kurumsal Uzman Yardımcısı": "Junior corporate specialist",
    "Aile Yanında": "Living with family",
    "Paylaşımlı Ev": "Shared flat",
    "Tek Başına Stüdyo": "Studio alone",
    "Selin düzenli bir işe geçti.": "Selin took a steady job.",
    "Selin kendi düzenini kurdu.": "Selin built a life of her own.",
    "Emre eğitimine devam ediyor.": "Emre is staying in school.",
    "Burak yeni bir ekipte sorumluluk aldı.": "Burak took responsibility on a new team.",
    "Burak'la görüşmeleriniz seyrekleşti.": "You see Burak less often now.",
    "Aile evindeki kişisel alan ihtiyacı": "Need for personal space at the family house",
    "Selin yeni bir işe geçti; Emre eğitimine devam ediyor.": "Selin moved to a new job; Emre stayed in school.",
    "Çevrendeki insanların yolları senden farklı ilerliyor.": "People around you are moving on different tracks.",
    "Selin kendi düzenini kurdu; senin önceliklerin yeniden görünür oldu.": "Selin built her own order; your priorities came back into view.",
    "Bir üst pozisyon için değerlendirmeye girdin.": "You entered review for a higher post.",
    "Bir üst pozisyon teklifini bu kez erteledin.": "You deferred the higher-post offer this time.",
    "Terfi görüşmesi konusuz kaldı; o iş artık yok.": "The promotion talk went nowhere; that job is gone.",
    "Terfi değerlendirmesinde mevcut tempoda kaldın.": "In the promotion review you kept your current pace.",
    "Ay sonunu kapatmak için alınan geçici destek": "Short-term help taken to close the month",
    "İşteki yorgunluk ve performans riski": "Work fatigue and performance risk",
    "Performans değerlendirmesini geçtin; işin devam ediyor.": "You passed the performance review; the job continues.",
    "Performans düşüşü sonrası işini kaybettin.": "After the performance drop you lost the job.",
    "Emeklilik yerine bir yıl daha çalışmayı seçtin.": "You chose another year of work instead of retirement.",
    "Mütevazı": "Modest",
    "Rahat": "Comfortable",
    "Konforlu": "Well-off",
    "Yüksek": "High",
    "Film ve dizi": "Films and series",
    "Müzik": "Music",
    "Spor salonu": "Gym",
    "Hobi kulübü": "Hobby club",
    "Ev temizliği": "House cleaning",
    "Tanışma uygulaması": "Dating app",
    "Standart telefon": "Standard phone",
    "Yeterli bilgisayar": "Decent computer",
    "Ev eğlence sistemi": "Home entertainment set",
    "Kaliteli yatak": "Proper bed",
    "Ev çalışma düzeni": "Home work setup",
    "Ekonomik ikinci el": "Cheap second-hand",
    "Standart otomobil": "Standard car",
    "Konforlu otomobil": "Comfortable car",
    "Mevduat": "Deposit account",
    "Altın": "Gold",
    "Döviz sepeti": "FX basket",
    "Karma fon": "Mixed fund",
    "Hisse sepeti": "Equity basket",
    "Kahve molası": "Coffee break",
    "Paket yemek": "Takeaway",
    "İyi bir akşam yemeği": "A proper dinner",
    "Saç ve kişisel bakım": "Hair and grooming",
    "Günlük kıyafet yenileme": "Everyday clothes refresh",
    "İş kıyafeti": "Work clothes",
    "Evde küçük onarım": "Small home repair",
    "Tek seferlik ev temizliği": "One-off house clean",
    "Anlamlı hediye": "A gift that means something",
    "Kafe ve arkadaş buluşması": "Café with friends",
    "Sinema / gösteri": "Cinema / show",
    "Tiyatro / stand-up": "Theatre / stand-up",
    "Konser / canlı müzik": "Concert / live music",
    "Evde film ve müzik akşamı": "Film-and-music night at home",
    "Oyun akşamı": "Game night",
    "Kitap ve sakin akşam": "Book and a quiet night",
    "Hobi dersi / atölye": "Hobby class / workshop",
    "Yüzme / spor etkinliği": "Swim / sports session",
    "Bar / gece hayatı": "Bar / night out",
    "Romantik akşam": "Romantic evening",
    "Özel hafta sonu": "A special weekend",
    "Günübirlik gezi": "Day trip",
    "Hafta sonu kaçamağı": "Weekend getaway",
    "Yurt içi tatil": "Domestic holiday",
    "Yurt dışı tatil": "Holiday abroad",
    "İşsiz — ulaşım yükü yok": "Unemployed — no commute load",
    "Genç yetişkinlik": "Young adulthood",
    "Orta kariyer": "Mid-career",
    "Orta yaşam": "Midlife",
    "Geç kariyer": "Late career",
    "Emeklilik dönemi": "Retirement years",
    "Tek bir hayatı haftalık kararlarla yönetiyorsun. Kariyer, para, ilişkiler ve sağlık birbirini etkiler; amaç mükemmel bir plan değil, sürdürülebilir bir denge kurmak.": "You run one life through weekly choices. Work, money, relationships and health pull on each other. The aim is not a perfect plan — it is a pace you can keep.",
    "Her hafta 2 karar hakkın var (sağlığın kritikse 1'e düşer). Karar hakkını iş/sosyal/aktivite kararlarına harcadıktan sonra haftayı ilerlet; maaş, kira ve düzenli giderler ay sonunda otomatik işler.": "You get two decisions a week (one if health is critical). Spend them on work, people or activities, then advance the week. Pay, rent and regular bills land at month-end on their own.",
    "Her hafta 6 zaman/odak bloğun var (sağlığın kritikse 3'e düşer). İş, eğitim, aile ve sosyal hayat aynı bütçeyi paylaşır; haftayı erken kapatabilir, yorgunluk ve ertelenen sonuçları göze alabilirsin. Maaş, kira ve düzenli giderler ay sonunda otomatik işler.": "You get six time/focus blocks each week (three when health is critical). Work, education, family and social life share that budget; you can close the week early and accept fatigue or deferred consequences. Pay, rent and regular bills settle at month-end.",
    "Üstteki menüden Ana Sayfa, Ben, Takvim, Para, İş, Eğitim, Kişiler, Aile/İlişkiler, Ev, Beden, Geçmiş ve Yıl Dosyası bölümlerine geçersin. Bazı seçimler ayrı bir olay penceresi açar; orada verdiğin cevap haftayı ilerletmeden hemen uygulanır.": "The top menu moves you through Home, Me, Calendar, Money, Work, Education, People, Family/Relations, Home, Body, History and Year File. Some choices open a separate event; the answer there applies at once, without advancing the week.",
    "İş bulmak, terfi ve eğitim Para'yı doğrudan etkiler. Para ekranı bakiye, aylık gelir/gider ve net servetini gösterir: nakit, yatırım, gayrimenkul, araç/eşya ve borçların toplamı. Yaşam standardını (mütevazıdan yükseğe) ve abonelik/eşya harcamalarını da buradan yönetirsin.": "Finding work, promotion and school hit Money directly. That screen shows balance, monthly in/out and net worth: cash, investments, property, goods and debts. You also set living standard and subscriptions there.",
    "Beden ekranı enerji/stres/sağlığını, Takvim bekleyen randevu ve gecikmiş sonuçlarını, Yıl Dosyası her yılın özetini tutar. Kişiler ve Aile/İlişkiler sekmeleri güven, yakınlık ve gerilim gibi ilişkisel göstergeleri taşır.": "Body tracks energy, stress and health. Calendar holds pending appointments and late results. Year File keeps each year's digest. People and Family/Relations carry trust, closeness and tension.",
    "İhmal edilen sağlık karar hakkını düşürür ve iş performansını etkiler; ihmal edilen ilişkiler zamanla soğur. Kararların bazı sonuçları hemen değil, haftalar sonra bir olay olarak geri döner.": "Neglected health cuts your decision count and work performance. Neglected ties cool off. Some consequences do not land now — they return weeks later as an event.",
    "Oyun tarayıcının yerel deposuna otomatik kaydedilir; üstteki Kaydet ile elle de kaydedebilirsin. Yeni oyun, mevcut hayatı tamamen siler ve onay ister.": "The game autosaves in this browser. Use Save in the header to write it by hand. New Game wipes the current life and asks first.",
    "Önce bir iş bul ve birkaç hafta düzen kur. Sağlığın kritik seviyeye inmeden dinlenmeye zaman ayır. Elindeki parayı hepsini harcamadan bir miktar nakit tut. Aile ve yakın çevrenle bağını koparma; ilerideki birçok fırsat bu bağa dayanır.": "Find work first and settle a few weeks. Rest before health turns critical. Keep some cash. Do not cut family and close friends; later doors hang on those ties.",
    "60'lı yaşlardan sonra yeterli çalışma geçmişiyle emekliliği değerlendirebilirsin. Hayat sona erdiğinde bir Yaşam Raporu çıkar ve varsa yetişkin bir çocuğunla yeni bir kuşak olarak devam edebilirsin; servetin ve aile bağların bir sonraki hayata iz bırakır.": "From your sixties, with enough work history, you can weigh retirement. When the life ends you get a Life Report, and if you have an adult child you can continue as the next generation. Wealth and family ties leave a mark.",
    "Görüş": "Meet",
    "Dertleş": "Talk it out",
    "Arayı düzelt": "Mend the gap",
    "İlişkiyi ileri taşı": "Take the relationship forward",
    "Elif'in aile evinde gizlice kalması": "Elif staying secretly at the family house",
    "Mehmet'in işindeki belirsizlik": "The uncertainty in Mehmet's job",
    "Günlük temposunu etkileyen bilinen beden durumu": "A known body issue that shapes the daily pace",
    "Gebelik haberi": "Pregnancy news",
    "Dengeli başlangıç": "Balanced start",
    "Hırslı başlangıç": "Ambitious start",
    "Sosyal başlangıç": "Social start",
    "Kuzen": "Cousin",
    "Eski sınıf arkadaşı": "Old classmate",
    "Özel bir mesele": "A private matter",
    "Annen stüdyoya habersiz geldi": "Your mother showed up at the studio unannounced",
    "Çocuk niyetini yeniden görüş": "Talk children through again",
    "Bakım bütçesini planla": "Plan the care budget",
    "Çocuğunun bakımına zaman ayır": "Give time to your child's care",
    "Ek mesai yap": "Work overtime",
    "Aileyle vakit geçir": "Spend time with family",
    "Mehmet'le buluş": "Meet Mehmet",
    "Bedenine bakım ayır": "Give the body some care",
    "Spor yap": "Exercise",
    "Mehmet'in başvurusuna yardım et": "Help Mehmet with an application",
    "Mehmet'e borç ver": "Lend Mehmet money",
    "Sakin bir akşam geçir": "Have a quiet evening",
    "Temponu düzenle": "Reset your pace",
    "Bütçeyi gözden geçir": "Review the budget",
    "İş fırsatlarını araştır": "Look for work openings",
    "Aylin'i ara": "Call Aylin",
    "Mehmet'e ulaş": "Reach Mehmet",
    "Paylaşılan maddi durum": "Shared money situation",
    "Teknik": "Technical",
    "İşletme": "Business",
    "Kısa süreli, çalışırken sürdürülebilir teknik program.": "A short technical program you can keep while working.",
    "Uzun soluklu lisans programı; bitince yeni kariyer kapısı açar.": "A long degree track; finishing it opens a new career door.",
    "Başlangıç": "Starter",
    "Deneyimli": "Experienced",
    "Kıdemli": "Senior",
    "Bir arkadaşa": "To a friend",
    "Biri": "Someone",
    "Emekli — iş ulaşımı yok": "Retired — no work commute",
    "Bir olay": "An event",
    "Evliliğinizdeki ayrılık kararı": "The separation decision in your marriage",
    "Boşanma kararınız": "Your divorce decision",
    "Çocuk konusundaki kişisel niyetleriniz": "Your private stance on children",
    "Partnerinle birlikte kurduğun yaşam düzeni": "The household you built with your partner",
    "Evlilik kararınız": "Your marriage decision",
    # Kayıp Telefon
    "kız kardeş": "sister",
    "kısa, endişeli": "short, anxious",
    "resmi-yamuk": "formal-crooked",
    "eski ev arkadaşı": "old housemate",
    "kapalı": "closed",
    "eski ilişki": "ex",
    "lâubali": "too familiar",
    "yeni isim": "new name",
    "kısa": "brief",
    "üst": "boss",
    "nerdesin ya": "where are you even",
    "annem sordu": "mom asked",
    "telefonun cekmiyo belki": "maybe no signal",
    "yemege gelmicen dimi": "youre not coming to dinner right",
    "dosya mailde": "file is in the mail",
    "müşteri 16:00ı bekliyo": "client waiting at 16:00",
    "imza atmadan çıkarma": "dont leave without the signature",
    "bu maili iletme": "dont forward this mail",
    "bunu kimse bilmemeli": "nobody should know this",
    "cuma değil cumartesi": "not friday saturday",
    "adres aynı değil": "address is not the same",
    "sil bunu": "delete this",
    "anahtarı bıraktım": "i left the key",
    "kutular sende kalsın": "keep the boxes",
    "konuşacak bişey yok": "nothing to talk about",
    "abi nakit lazım": "bro i need cash",
    "çarşamba netleşir": "wednesday it firms up",
    "annene söyleme": "dont tell your mom",
    "geldin mi": "you here yet",
    "kafede kimse olmasın": "nobody at the cafe",
    "foto atma": "dont send a photo",
    "toplantı 09:30 kaydırma": "meeting 09:30 dont slip it",
    "müşteri bekler": "the client waits",
    "bu maili dışarı taşıma": "dont take this mail outside",
    "ilac hazır": "medicine ready",
    "son 1 gün": "last 1 day",
    # Çete hoods / jobs / items — proper place names kept
    "Türbe çıkışı, turist, sahte tespih. Kalabalıkta kaybolursun.": "Shrine gate, tourists, fake prayer beads. You vanish in the crowd.",
    "Pavyon ve tombala işlerinde başarı +6%": "Pavilion and bingo jobs +6% success",
    "Dar sokak, basık Tofaş, köşe başı. Kaçacak delik çoktur.": "Narrow street, dropped Tofaş, corner. Plenty of holes to slip through.",
    "Mermi & Takat tavanı +4. Torbacı köşesi +20%": "Rounds & Stamina cap +4. Dealer corner +20%",
    "Moda iskele, bar, kabadayı. Gece burada biter.": "Moda pier, bars, hard men. Night ends here.",
    "Emlak geliri +15%": "Property income +15%",
    "Mahalle ağı, senet, okey. Para sessiz akar.": "Neighborhood net, IOUs, okey. Money moves quiet.",
    "Saldırı +5": "Attack +5",
    "Torba Tutma ve Köşe Başları": "Bags and street corners",
    "Pavyon Çıkışı Sarhoş Soyma": "Roll a drunk leaving the pavilion",
    "Konsomatrislere para saçıp sızan tiplerin cüzdanını tırtıkla.": "Pick the wallets of men who spent the night throwing cash at hostesses.",
    "Korsan Kumarhane ve Tombala Oynatmak": "Run a pirate hall and bingo",
    "Polis basmasın diye kapıya gözcü koy, kaçak tombala çevir.": "Put a lookout on the door and keep the illegal bingo turning.",
    "Torbacılık ve Mahalle Dağıtımı": "Dealing and neighborhood drops",
    "Egea ile sokak arası teslimat. Konum atma, elden teslim, dikiz.": "Street drops in an Egea. No pins, hand to hand, watch the mirrors.",
    "POS Kopya / Yazar Kasa": "Cloned POS / till",
    "Büfe POS'una klon. Küçük çekimler, büyük iz bırakma.": "Clone the kiosk POS. Small pulls. Leave no fat trail.",
    "Hurda Bakır ve Kablo": "Scrap copper and cable",
    "Şantiye gece, kablo makarası, hurdacı nakit. Gürültü senin aleyhine.": "Night site, cable reels, scrap-yard cash. Noise works against you.",
    "Mahalle Kontrolü": "Neighborhood control",
    "Sahte Kutu Telefon (Merter)": "Fake boxed phone (Merter)",
    "Kapalı kutu iPhone, içi tuğla. Telegram'dan alıcı, Merter'den çıkış.": "Sealed iPhone box, brick inside. Buyer on Telegram, exit through Merter.",
    "Kaçak Bahis Tahsilatı": "Illegal-book collection",
    "Site bakiyesi eksiye düşenleri evinden kaldır. IBAN değil, nakit.": "Lift the men whose site balance went red. Cash, not IBAN.",
    "İnşaat Sahası Haraç": "Site tribute",
    "Kalfa 'güvenlik' diye yazar. Sen çay içersin, kasa dolar.": "The foreman writes it as 'security'. You drink tea. The till fills.",
    "Sahte Bahis Reklamı": "Fake betting ads",
    "Instagram'da 'kesin yatan' kupon. Ödemeyen site, sen komisyon.": "Instagram 'locks' coupons. The site never pays. You take commission.",
    "Sahte Ekspertiz / Galeri": "Fake inspection / showroom",
    "Kilometre düşür, hasar gizle, sahibinden'de 'hatasız' yaz.": "Drop the mileage, hide the hit, list it 'clean' on Sahibinden.",
    "Baronluğa Doğru Racon": "Racon toward baron",
    "İhale Savaşları ve Tehdit": "Tender wars and threat",
    "Belediye ihalesine giren müteahhidin ofisine kon, çekilmesini söyle.": "Sit in the contractor's office and tell him to leave the municipal tender.",
    "Gümrükten Kaçak Mal Geçirme (Ambarlı)": "Move contraband through customs (Ambarlı)",
    "Gece yarısı konteyner, memura zarf, TIR'a GPS. Ambarlı çıkışı.": "Midnight container, envelope for the clerk, GPS on the truck. Ambarlı exit.",
    "Villa ve Kasa Basma": "Villa and safe job",
    "Sarıyer yamaç, kamera kör, kasa duvarda. Köpek ayrı mesele.": "Sarıyer slope, cameras blind, safe in the wall. The dog is another problem.",
    "Kapalıçarşı Kuyum Tırnak": "Grand Bazaar jeweler lift",
    "Kepenk inmeden vitrin. Gram altın, kaçış Eminönü altı.": "Window before the shutter drops. Gram gold. Exit under Eminönü.",
    "Kırık Efes Şişesi": "Broken Efes bottle",
    "Lounge çıkışı, kadeh değil şişe. Hâlâ iş görür.": "Leaving the lounge. Not a glass — a bottle. Still does the job.",
    "Kelebek Bıçak (Karambit)": "Karambit",
    "TikTok kabadayılarının belinde. Cebe sığar, laf dinletir.": "On the belt of TikTok hard men. Fits a pocket. Makes people listen.",
    "Hayalet Canik TP9": "Ghost Canik TP9",
    "Numarasız, merdiven altı. Tetikte tutukluk yapma riski var.": "No serial, under-stairs shop. Trigger can jam.",
    "Sarsılmaz SAR9 Mega": "Sarsılmaz SAR9 Mega",
    "Yerli üretim, bel holster. Ofis masasına kondu mu konuşma biter.": "Domestic make, belt holster. On the desk, the talk ends.",
    "Draco (Kısa Namlulu AK)": "Draco (short AK)",
    "Range Rover'ın arka koltuğundan çıkan kısa namlu. Mahalle değil, konvoy silahı.": "Short barrel off a Range Rover back seat. Not a street piece — a convoy piece.",
    "Sarsılmaz 12 Kalibre": "Sarsılmaz 12-gauge",
    "Kısa namlu pompalı. Kapı arkasında konuşur.": "Short pump. It talks from behind the door.",
    "Glock 19 (Klon)": "Glock 19 (clone)",
    "Avusturya değil, merdiven altı. Yine de masada durur.": "Not Austria — under-stairs. Still sits on the table.",
    "Stone Island Mont + Tespih": "Stone Island coat + beads",
    "Pusula omuzda, tespih parmakta. 2020'ler İstanbul'unun üniforması.": "Compass on the shoulder, beads on the finger. 2020s Istanbul uniform.",
    "Plaka Yelek (Hoodie Altı)": "Plate vest (under the hoodie)",
    "North Face altı sac. Dışarıdan spor, içeriden plaka.": "Sheet steel under a North Face. Sport outside, plate inside.",
    "Zırhlı Makam Takımı": "Armored office suit",
    "Loro Piana kesim, içi Kevlar. Cenazeye de gider, basmaya da.": "Loro Piana cut, Kevlar inside. Works for a funeral and a raid.",
    "CP Company Gözlük + Mont": "CP Company glasses + coat",
    "Lens ayna, mont şişme. 2024 kabadayı üniforması.": "Mirror lenses, puffer coat. 2024 hard-man kit.",
    "Makam Palto (Kaşmir)": "Office overcoat (cashmere)",
    "Kış, rüzgar, itibar. İçinde plaka yok ama duruş var.": "Winter, wind, reputation. No plate inside — there is posture.",
    "Çalıntı Fiat Egea": "Stolen Fiat Egea",
    "Sahte plaka, basık jant. Dar sokakta kaybolmanın güncel hali.": "Fake plate, dropped rims. Today's way to vanish in a narrow street.",
    "Siyah Camlı BMW 520d": "Blacked-out BMW 520d",
    "Makam plaka, çakarsız. EDS yese de çevirme ayrı mesele.": "Office plate, no flashers. Cameras still bite; a stop is another matter.",
    "Zırhlı Range Rover": "Armored Range Rover",
    "Konvoyun önü. Cam film yasal değil, zırh paket yasal değil, durmak yok.": "Front of the convoy. Tint is illegal, armor pack is illegal, stopping is not an option.",
    "Mercedes Vito (Ekip)": "Mercedes Vito (crew)",
    "Koltuk arkası boş, sürgü kapı. Mahalle turu ve kaçış aynı araç.": "Empty behind the seats, sliding door. Neighborhood tour and the exit are the same van.",
    "Honda Forza (Plakasız)": "Honda Forza (no plate)",
    "Dar sokak, kaldırım, tek kişi. Yakalanırsan motor senden hızlı değil.": "Narrow street, pavement, one rider. If they catch you the bike is not faster than you.",
    "Togg T10X (Sahte)": "Togg T10X (forged)",
    "Yerli elektrikli, sahte ruhsat. EDS yine yer, şarj ayrı dert.": "Domestic EV, forged papers. Cameras still bite. Charge is another headache.",
    "Mercedes E200 Cam Film": "Mercedes E200 tint",
    "Makamın sessiz hali. Şoför önde, sen arkada.": "The quiet office car. Driver up front, you in the back.",
    "Çalıntı Bisiklet": "Stolen bicycle",
    "Dar sokak, tek vites. Yakalanırsan pedal senden hızlı değil.": "Narrow street, one speed. If they catch you the pedals are not faster than you.",
    "Porsche 911 (Sahte Ruhsat)": "Porsche 911 (forged papers)",
    "Kanyon çıkışı, EDS yer, sen çoktan sapmışsındır.": "Out of Kanyon, cameras bite, you already turned off.",
    "Helikopter (Kaçak Pist)": "Helicopter (illegal strip)",
    "Silivri kenarı pist. Trafik yok, radar ayrı mesele.": "A strip on the Silivri edge. No traffic. Radar is another problem.",
    "iPhone 17 Pro Max": "iPhone 17 Pro Max",
    "Titanyum kasa, kırık cam ayrı. Masada durur, konuşulur.": "Titanium body, cracked glass is extra. It sits on the table and gets talked about.",
    "Rolex Datejust": "Rolex Datejust",
    "Bilekte çelik. Saat sormazlar, bakarlar.": "Steel on the wrist. Nobody asks the time. They look.",
    "Gram zincir + künye": "Gram chain + bracelet",
    "Kuyumcu tartar, mahalle tartmaz. Parıldar yeter.": "The jeweler weighs it. The street does not. Shine is enough.",
    "PS5 + 85 inç": "PS5 + 85-inch",
    "Okey salonunun ev hali. FIFA, nargile, kasa arkada.": "The okey hall, home edition. FIFA, nargile, till in the back.",
    "Air Jordan / CP set": "Air Jordan / CP set",
    "Ayakkabı kutusu dolu, etiket duruyor. Fotoğraf için.": "Boxes full, tags still on. For the photograph.",
    "Patek Nautilus (sahte seri)": "Patek Nautilus (fake serial)",
    "Baron bileği. Sahte olsa da cam öyle parlamaz.": "Baron wrist. Fake or not, glass does not shine like that.",
    "Mahalle Berberi / Tıraş": "Neighborhood barber",
    "Tıraş nakit, çay ikram. İş ~88 saat amorti.": "Cash cut, tea on the house. Pays back in ~88 hours of work.",
    "PlayStation & Okey Salonu": "PlayStation & okey hall",
    "Çay, FIFA, el altı kâğıt. ~89 saat amorti.": "Tea, FIFA, cards under the table. Pays back in ~89 hours.",
    "Nargile Cafe (Kaçak)": "Nargile café (unlicensed)",
    "Ocak, kömür, arka oda. ~91 saat amorti.": "Stove, coal, back room. Pays back in ~91 hours.",
    "Eyüp Lounge / Pavyon": "Eyüp lounge / pavilion",
    "Konsomatris, DJ, kasa. ~92 saat amorti.": "Hostess, DJ, till. Pays back in ~92 hours.",
    "Depo / Antrepo (Dudullu)": "Warehouse / depot (Dudullu)",
    "Koli, forklift. ~94 saat amorti.": "Crates, forklift. Pays back in ~94 hours.",
    "Tefeci Ofisi / Sahibinden Galeri": "Loan-shark office / used-car lot",
    "Senet, ikinci el Range. ~98 saat amorti.": "IOUs, second-hand Range. Pays back in ~98 hours.",
    "Boğazda Kaçak Casino": "Illegal Bosphorus casino",
    "VIP kumar. ~100 saat amorti.": "VIP tables. Pays back in ~100 hours.",
    "Kadıköy Stüdyo": "Kadıköy studio",
    "Tek oda. Kira ince, ~520 saat.": "One room. Thin rent. ~520 hours.",
    "Ataşehir 3+1": "Ataşehir 3+1",
    "Site, havuz. ~520 saat.": "Gated site, pool. ~520 hours.",
    "Sarıyer Villa": "Sarıyer villa",
    "Manzara, bahçe. Konut ~533 saat.": "View, garden. Housing ~533 hours.",
    "Bebek Yalı Katı": "Bebek yalı floor",
    "Boğaz, cam. Villadan pahalı, ~537 saat.": "Bosphorus, glass. Dearer than a villa. ~537 hours.",
    "Göcek Özel Ada": "Göcek private island",
    "İskele senin. ~568 saat.": "The pier is yours. ~568 hours.",
    "Gram altın": "Gram gold",
    "Dolar": "Dollar",
    "USDT": "USDT",
    "Tek köşe": "One corner",
    "Bir kavşak. Haftalık gelir. Emniyet basar, baskında köşe susar.": "One junction. Weekly take. Police hit it and the corner goes quiet.",
    "Mahalle ağı": "Neighborhood net",
    "Birkaç köşe tek elden. Getiri şişer, devriye de.": "Several corners in one hand. Yield swells. So do the patrols.",
    "Semt hattı": "District line",
    "Semtin kâğıdı sende. Haftalık ağır, baskın da ağır.": "The district paper is yours. Heavy week. Heavy raid.",
    "Gözcü Selim": "Lookout Selim",
    "Yakalanma −18%. Baskın ve ihanet daha seyrek.": "Pinch −18%. Raids and betrayal land less often.",
    "Şoför Kenan": "Driver Kenan",
    "İcraat mermi maliyeti −2.": "Job round cost −2.",
    "Tahsildar Leyla": "Collector Leyla",
    "Emlak ve semt geliri +15%.": "Property and district income +15%.",
    "Tetikçi Rıdvan": "Trigger Rıdvan",
    "Saldırı +10. Sokak daha kısa kesilir.": "Attack +10. The street ends quicker.",
    "Avukat Cemil": "Lawyer Cemil",
    "Yakalanma −25%. Zarf ucuzlar.": "Pinch −25%. The envelope gets cheaper.",
    "Pavyon çıkışı kirlendi. Sarhoşu sen temizle, hesap bende.": "The pavilion door is dirty. You clean the drunk. The bill is mine.",
    "Bu gece masayı sen çevir. Polis başka semtte, diyorlar.": "You turn the table tonight. They say police are in another district.",
    "Üç durak. Egea hazır. Konum atarım, sen götür.": "Three stops. Egea ready. I drop a pin, you run it.",
    "Merter'de kutu bekliyor. Alıcı Telegram'da. Tuğla konuşulmaz.": "A box waits in Merter. Buyer on Telegram. Nobody says brick.",
    "Site bakiyesi eksiye düşen var. Tahsilat nakit, IBAN yok.": "Someone's site balance went red. Collection in cash. No IBAN.",
    "Şantiye 'güvenlik' yazacak. Sen çay iç, kasa dolsun.": "The site will write 'security'. You drink tea. The till fills.",
    "İhale adamı çekilmiyor. Ofisine kon. Range aşağıda bekler.": "The tender man will not step off. Sit in his office. The Range waits downstairs.",
    "Ambarlı gece. Konteyner, zarf, GPS kapalı. Sen bilirsin.": "Ambarlı at night. Container, envelope, GPS off. You know the rest.",
    "POS'u bir gece klonla. Küçük çekim, iz yok.": "Clone the POS for one night. Small pull. No trail.",
    "Bakır bu gece. Makarayı sen kaldır.": "Copper tonight. You lift the reel.",
    "Kupon sayfası hazır. Sen reklamı bas, komisyon bende.": "The coupon page is ready. You push the ads. Commission is mine.",
    "Galeriye kilometre lazım. Hatasız yazacağız.": "The lot needs mileage dropped. We will list it clean.",
    "Sarıyer'de kasa. Köpek var, kamera kör.": "A safe in Sarıyer. There is a dog. Cameras are blind.",
    "Çarşı kepenk inmeden. Gramlar senin.": "Bazaar before the shutter. The grams are yours.",
    "Galata kabadayısı": "Galata hard man",
    "Kaçak kumar işletmecisi": "Illegal-gambling operator",
    "Telegram dolandırıcısı": "Telegram grifter",
    "Tarlabaşı torbacısı": "Tarlabaşı dealer",
    "İhale aracısı": "Tender fixer",
    "Tetikçi": "Trigger man",
    "Liman gözcüsü": "Port lookout",
    "Pavyon patronu": "Pavilion boss",
    "Boğaz'ın sessiz ortağı": "Quiet Bosphorus partner",
    "Sanayi kabadayısı": "Industrial-zone hard man",
    "Tarlabaşı kiralık öfke": "Tarlabaşı hired temper",
    "Senet tahsildarı": "IOU collector",
    "Lounge kasa ortağı": "Lounge till partner",
    "Lounge DJ": "Lounge DJ",
    "Kulaklık boynunda, gece Galata. Lafı kısa keser.": "Headphones on the neck, Galata at night. She cuts talk short.",
    "Stajyer avukat": "Trainee lawyer",
    "Levent ofisi, dosya kokusu. Raconu mahkeme diline çevirir.": "Levent office, file smell. She turns racon into court language.",
    "Galeri satışı": "Showroom sales",
    "Sahibinden değil, vitrin. Range'i o satar, sen bakarsın.": "Not a listing — a window. She sells the Range. You watch.",
    "Kasa / pavyon": "Till / pavilion",
    "Hesabı o tutar. Masaya oturunca semt duyar.": "She keeps the books. When she sits, the district hears.",
    # Extra event results commonly shown
    "Kısa çıkış": "Short outburst",
    "Akşam yemeği": "Dinner",
    "Paylaşılan hesap": "Shared account",
    "Eğitim belgeni aldın.": "You collected your diploma.",
    "Sosyal buluşma": "Social meetup",
    "Aile desteği": "Family support",
    "Maddi sıkıntıyı kendi başına çözmeyi seçtin.": "You chose to solve the money pinch alone.",
    "Yoğun temponun ardından yavaşlamayı seçtin.": "After the heavy pace you chose to slow down.",
    "Yoğun tempo": "Heavy pace",
    "Mehmet'in iş görüşmesini birlikte kutladınız.": "You marked Mehmet's interview together.",
    "Sağlığın için yardım aldın.": "You took help for your health.",
    "Sağlık gideri": "Health cost",
    "İlk iş değerlendirmeni sorunsuz tamamladın.": "You finished your first job review clean.",
    "İşinde daha fazla sorumluluk istedin.": "You asked for more responsibility at work.",
    "İş primi": "Work bonus",
    "Lisans diploman yeni bir iş fırsatının kapısını açtı.": "Your degree opened a new job door.",
    "Deneyimin sayesinde daha iyi bir iş fırsatı doğdu.": "Experience opened a better job.",
    "Ders ve iş yükü arasında tempoyu düşürdün.": "You dropped pace between class and work.",
    "Eğitim desteği": "Education support",
    "Eğitim ücreti için ailenden destek istedin.": "You asked family to help with school fees.",
    "Eğitim ücretini karşılamak için harcamalarını kıstın.": "You cut spending to cover school fees.",
    "İş yüküne karşı sınır koydun.": "You put a limit on the workload.",
    "Yoğun iş primi": "Heavy-work bonus",
    "Durumu değerlendir": "Weigh the situation",
    "Temponu düşür ve takip planla": "Drop the pace and plan follow-up",
    "Aynı tempoda devam et": "Keep the same pace",
    "Toparlanma için zaman ve takip planla": "Plan time and follow-up to recover",
    "Şimdilik önemseme": "Leave it for now",
    "Hareket için zaman ve takip planla": "Plan time and follow-up for movement",
    "Böyle devam et": "Keep going like this",
    "henüz konuşulmadı": "not talked through yet",
    "okumaya yakın": "leaning toward study",
    "çalışmaya yakın": "leaning toward work",
    "henüz net değil": "not clear yet",
    "okuma yönünde": "toward study",
    "çalışma yönünde": "toward work",
    "yönü henüz açık": "direction still open",
    "Küçük çocukluk": "Early childhood",
    "Erken çocukluk": "Young childhood",
    "zorlanıyor": "struggling",
    "Henüz konuşulmadı": "Not talked through yet",
    "İleride çocuk istiyorum": "I want children later",
    "Çocuk istemiyorum": "I do not want children",
    "Emin değilim": "I am not sure",
    "Ayrı yaşıyor · evli": "Living apart · married",
    "Birlikte yaşıyorsunuz": "You live together",
    "Ayrı yaşam düzeni": "Separate living arrangement",
    "Beklentisi yüksek aile": "High-expectation family",
    "Sıkışık başlangıç": "Tight start",
    "Mütevazı başlangıç": "Modest start",
    "Yarım kalmış eğitim": "Unfinished schooling",
    "Yakın çevre": "Close circle",
    "Geniş çevre": "Wide circle",
    "Atılgan": "Forward",
    "Dağınık": "Scattered",
    "İçe dönük": "Inward",
    "Harcamacı": "Spender",
    "Para ve borç": "Money and debt",
    "Sağlık": "Health",
    "Yakınlık": "Closeness",
    "Güven": "Trust",
    "Bağlam değişir": "The context shifts",
    "Tanışık": "Acquainted",
    "Arkadaş": "Friend",
    "Yakın": "Close",
    "İş bağlantısı": "Work contact",
    "Tanıdık": "Familiar",
    "Çok düşük": "Very low",
    "Düşük": "Low",
    "bağımsız yaşam": "independent life",
    "aile desteğiyle yaşam": "life with family support",
    "Eğitimine devam ediyor": "Still in school",
    "Çalışma hayatında": "In working life",
    "Yönünü değerlendiriyor": "Weighing a direction",
    "İleri yaş": "Later age",
    "Uzun süreli sağlık yükü": "Long-term health load",
    "Sağlıkta uzun süreli gerileme": "Long decline in health",
    "Bu yaşam tamamlandı. Yaşam raporunu inceleyebilir, uygunsa bir yetişkin çocukla devam edebilirsin.": "This life is complete. Read the life report, and if it fits continue with an adult child.",
    # Racon / Hanedan / Bükücü chrome
    "Adsız": "Nameless",
    "Menüyü aç": "Open menu",
    "Menüyü daralt": "Collapse menu",
    "Hafta yeni başladı.": "The week just started.",
    "Saygı": "Respect",
    "Hasım": "Rival",
    "güçlü": "strong",
    "zayıf": "weak",
    "Şehir": "City",
    "Baskın": "Raid",
    "Toplayıcı": "Collector",
    "Gözcü": "Lookout",
    "Sürücü": "Driver",
    "Baba adayı": "Heir",
    "Soğukkan": "Cold blood",
    "Çeviklik": "Agility",
    "Şöhret": "Fame",
    "Kıskanç": "Jealous",
    "Kana susamış": "Blood-hungry",
    "İLERLET": "ADVANCE",
    "Vazgeç": "Back out",
    "Hapisten çıkan": "Out of prison",
    "Köyden gelen": "From the village",
    "Borçlu": "In debt",
    "Mahalleye adsız girilmez. Nereden geldin?": "You do not enter the neighborhood nameless. Where did you come from?",
    "İlk gece.": "First night.",
    "Emin misin? Bu kayıt gider.": "Sure? This save goes.",
    "Kısaca, kolay Türkçe.": "Short, plain Turkish.",
    "Oyun ne anlatıyor": "What the game is",
    "Başlarken": "At the start",
    "Ana döngü: İLERLET": "Core loop: ADVANCE",
    "Menüdeki ekranlar": "Screens in the menu",
    "Olaylar": "Events",
    "Telefonu yan çevir": "Turn the phone sideways",
    "Menü": "Menu",
    "kâğıt": "paper",
    "şöhret": "fame",
    "YÖNETİCİ DOSYASI": "MANAGER FILE",
    "Bir bina, on altı daire, bitmeyen meseleler.": "One building, sixteen flats, issues that do not end.",
    "Meseleyi seç, dosyayı hazırla, Toplantı Gecesi'nde tek teklifi oylat ve haftayı kapat.": "Pick the issue, prepare the file, put one proposal to a vote on Meeting Night, close the week.",
    "YÖNETİM DOSYASI": "MANAGEMENT FILE",
    "1978 yapımı, 16 daire. Anahtar, ilan panosu ve hesap defteri sana geçecek.": "Built 1978, 16 flats. Keys, notice board and ledger pass to you.",
    "açık mesele": "open issue",
    "GERİ": "BACK",
    "YÖNETİMİ DEVRAL": "TAKE MANAGEMENT",
    "hazırlandı": "prepared",
    "YÖNETİCİ DEFTERİ": "MANAGER LEDGER",
    "Yönetici Masası": "Manager Desk",
    "BİNA": "BUILDING",
    "SON 100 GÜN": "LAST 100 DAYS",
    "Yüz gün. Günde iki karar. Her şeyi kurtaramazsın.": "A hundred days. Two decisions a day. You cannot save everything.",
    "SENARYONU SEÇ": "CHOOSE YOUR SCENARIO",
    "Başlangıç yükün sessizce seçilmez. On sekiz senaryodan birini belirle.": "The starting load is never chosen in silence. Pick one of eighteen scenarios.",
    "ÖNERİLEN": "RECOMMENDED",
    "ilişki yükü": "relationship load",
    "100 GÜNÜ BAŞLAT": "BEGIN 100 DAYS",
    "FİNAL RAPORU": "FINAL REPORT",
    "Yüz gün bitti": "A hundred days are over",
    "Yakalanan fırsat": "Caught opportunity",
    "Kaçan fırsat": "Missed opportunity",
    "BULUNAN CİHAZ": "FOUND DEVICE",
    "Bir telefon bulundu. İçindeki hayat sana ait değil.": "A phone was found. The life inside it is not yours.",
    "Açık uygulamalardaki öğeleri incele. Her dokunuş bulgu üretirken mahremiyet bedelini artırabilir. Telefonu istediğin an iade edebilirsin.": "Inspect items in the open apps. Each tap can yield a clue and raise the privacy cost. You can return the phone whenever you want.",
    "BİLDİRİM": "NOTICE",
    "Bu telefon senin değil.": "This phone is not yours.",
    "TELEFONU AÇ": "OPEN PHONE",
    "SAHİBİ BİLİNMİYOR": "OWNER UNKNOWN",
    "Fotoğraflar": "Photos",
    "Ses Kayıtları": "Voice records",
    "dosya kapandı": "file closed",
    "keşif": "discovery",
    "Yetişkin çocuk": "Adult child",
    "Çocuk planını görüşme": "Talk through a child plan",
    "Doğum hazırlığı": "Birth preparation",
    "Doğum zamanı": "Time of birth",
    "Bakım düzenini görüşme": "Talk through the care setup",
    "Çocuk giderlerini görüşme": "Talk through child costs",
    "Aile desteğini görüşme": "Talk through family support",
    "Çocuk için yaşam alanı": "Living space for a child",
    "Aile görüşmesi": "Family talk",
    "Ortak ev kararı": "Shared-home decision",
    "Ev sorumluluklarını görüşme": "Talk through house duties",
    "Evlilik kararı": "Marriage decision",
    "Kışla-Devlet": "Garrison-State",
    "Bürokrasi-Devlet": "Bureaucracy-State",
    "Bölgesel-Devlet": "Regional-State",
    "Popülist-Devlet": "Populist-State",
    "resmi yazı": "official note",
    "sendika fısıltısı": "union whisper",
    "sosyal ağ": "social network",
    "arşiv notu": "archive note",
    "İskân planı yürürlükte.": "The settlement plan is in force.",
    "Defterde yerimiz yazılmış, odada yok.": "Our place is written in the ledger, not in the room.",
    "Sayılar sonradan düzeltilir.": "The numbers get corrected later.",
    "1923 Ekim → 2030 Aralık. Hedefsiz veya doktrinli.": "October 1923 → December 2030. Open-ended or under a doctrine.",
    "Merkezileşme": "Centralization",
    "Yerel özerklik": "Local autonomy",
    "Kurumsallık": "Institutionalism",
    "Müzakere": "Negotiation",
    "Açıklık": "Openness",
    "İşsizlik": "Unemployment",
    "Borç": "Debt",
    "Tarım": "Agriculture",
    "Dış bağımlılık": "External dependence",
    "Barınma": "Housing",
    "Yükümlülük": "Duty",
    "Hırs": "Ambition",
    "Çevre": "Network",
    "Pişmanlık": "Regret",
    "Alışkanlık": "Habit",
    "Yurttaşlık": "Civic",
    "Aile parası": "Family money",
    "Dönüş": "Return",
    "İkinci şans": "Second chance",
    "Dönem": "Passage",
    "Eşik": "Milestone",
    "Kullanıcı adı ya da şifre yanlış.": "Username or password is wrong.",
    "Çıkılıyor…": "Signing out…",
    "Çıkış yap": "Sign out",
    "Gerçek bir e-posta yok.": "That is not a real email.",
    "Doğrulama maili tekrar gitti.": "The verification mail went again.",
    "Kullanıcı adı en az 3 karakter olmalı.": "Username must be at least 3 characters.",
    "Kullanıcı adı en fazla 24 karakter.": "Username can be at most 24 characters.",
    "Gerçek bir e-posta yaz.": "Write a real email.",
    "Şifre en az 8 karakter olmalı.": "Password must be at least 8 characters.",
    "Şifreler eşleşmiyor.": "Passwords do not match.",
    "Bu kullanıcı adı alınmış. Başka bir tane dene.": "That username is taken. Try another.",
    "Kayıt oldu. Doğrulama maili gitti — kutuyu kontrol et.": "Account created. Verification mail sent — check the box.",
    "İsimsiz": "Nameless",
    "Bir saat geçti. Sokak kendi işini gördü.": "An hour passed. The street did its own work.",
    "İş bitti.": "The job is done.",
    "İş patladı.": "The job blew.",
    "Devriye köşeyi döndü.": "The patrol turned the corner.",
    "Kaçtın.": "You ran.",
    "Tefeci Nuri notuna baktı. Kredi yok — önce senet kapat, itibar bas.": "Loan-shark Nuri checked his note. No credit — clear the IOU first, print some reputation.",
    "Soğuk bira. Can açıldı, racon gevşedi.": "Cold beer. Health opened. Racon loosened.",
    "Kıdem": "Rank",
    "Günlük seri": "Daily streak",
    "son kayıt": "last save",
    "Üst boş": "Chest empty",
    "Sıra": "Queue",
    "Sezon skoru. Birinci unvanı: İstanbul'un babası.": "Season score. First-place title: Father of Istanbul.",
    "4000 Yıllık Devlet Aklı": "Four Thousand Years of Statecraft",
    "Ucuz asansör yaması tutmadı": "The cheap elevator patch did not hold",
    "Ucuz yama tutmadı": "The cheap patch did not hold",
    "Ucuz asansör bakımı ikinci haftada ses yaptı.": "The cheap elevator job started rattling in the second week.",
    "Aidat isyanı: liste asılsın deniyor": "Dues revolt: they want the list posted",
    "Üst üste aidat artışı ödemeyi durdurdu.": "Back-to-back dues hikes stopped the payments.",
    "Bu görüşme artık açık değil.": "This talk is no longer open.",
    "Destek için ₺1.500 gerekiyor.": "Support needs ₺1,500.",
    "Devam edilecek tamamlanmış bir yaşam yok.": "There is no finished life to continue from.",
    "Kuşak kaydı doğrulanamadı.": "The generation record could not be verified.",
    "Geçerli bir yetişkin çocuk seçmelisin.": "You must pick a valid adult child.",
    "İşler": "Jobs",
    "Savcı": "Prosecutor",
    "Vazgeç": "Back out",
    "Hapisten çıkan": "Out of prison",
    "Köyden gelen": "From the village",
    "Düğün daveti": "Wedding invitation",
    "Otomatik değil. Birini seç. Kronik bunu yazar.": "Not automatic. Pick one. The chronicle writes it.",
    "Sokak doğanları": "Street-born",
    "Kuruluş": "Foundation",
    "Fikstür": "Fixture",
    "Mezarlık": "Graveyard",
    "Henüz kitabe yok.": "No epitaph yet.",
    "Kadrodan çıkar": "Drop from the roster",
    "Geri çekil": "Pull back",
    "Kıyas için iki aday işaretle.": "Mark two candidates to compare.",
    "Önce binaları sök": "Strip the buildings first",
    "Önce semtteki binaları sök": "Strip the buildings in the district first",
    "Kaçış / Kurum": "Escape / Institution",
}

# Common extra chrome used across shells
MAP.update({
    "Yeni labirent": "New maze",
    "Hamle": "Move",
    "Sıra sende": "Your turn",
    "Bilgisayar düşünüyor": "Computer is thinking",
    "Şah": "Check",
    "Şah mat": "Checkmate",
    "Pat": "Stalemate",
    "Berabere": "Draw",
    "Filoyu yerleştir": "Place the fleet",
    "Eksik filo": "Incomplete fleet",
    "İsabet": "Hit",
    "Iska": "Miss",
    "Battı": "Sunk",
    "Yeni tahta": "New board",
    "Kalan taş": "Stones left",
    "Tek taş kaldı": "One stone left",
    "Çıkış bulundu": "Exit found",
    "Duvara çarptın": "You hit a wall",
    "Adım": "Step",
})


def js_escape(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    items = sorted(MAP.items(), key=lambda kv: kv[0].casefold())
    lines = [
        "/**",
        " * Final EN overlay pack. Extends tlabI18n.PHRASE. Presentation only.",
        " */",
        "(function (root) {",
        "  const extra = {",
    ]
    for tr, en in items:
        lines.append(f"  {js_escape(tr)}: {js_escape(en)},")
    lines += [
        "  };",
        "  const I = root.tlabI18n;",
        "  if (!I || !I.PHRASE) return;",
        "  Object.assign(I.PHRASE, extra);",
        "  I.DEEP_EN_FINAL = extra;",
        "})(typeof window !== \"undefined\" ? window : globalThis);",
        "",
    ]
    out = ROOT / "public/i18n/deep-en-final.js"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", out, "entries", len(MAP))

    ts = [
        "/** Shared phrase overlay for React shells. Keep in sync with deep-en-final.js. */",
        "export const EXTRA_PHRASE: Record<string, string> = {",
    ]
    for tr, en in items:
        ts.append(f"  {js_escape(tr)}: {js_escape(en)},")
    ts += ["};", ""]
    ts_out = ROOT / "src/lib/i18n-phrases.ts"
    ts_out.write_text("\n".join(ts), encoding="utf-8")
    print("wrote", ts_out)


if __name__ == "__main__":
    main()
