import test from 'node:test';
import assert from 'node:assert/strict';
import {loadStrategy} from './strategy-harness.mjs';
const h=()=>{const g=loadStrategy('public/games/hanedan/legacy.html');g.ev('act("new:klasik");act("setupgo");draftPick=draftPool.slice(0,8).map(m=>m.id);act("draftok");');return g;};
const b=()=>{const g=loadStrategy('public/games/bukucu/index.html');g.ev('act("hot3")');return g;};
const json=(g,c)=>JSON.parse(g.ev('JSON.stringify('+c+')'));
test('Hanedan: production raid previews do not injure crew, retreat applies visited rooms once',()=>{const g=h();g.ev('S.men.forEach(m=>{m.hp=3;Object.keys(m.st).forEach(k=>m.st[k]=1)});before=JSON.stringify(S.men);act("ilerlet")');assert.equal(g.ev('JSON.stringify(S.men)===before'),true);g.ev('act("rback");after=JSON.stringify(S);act("rback")');assert.equal(g.ev('JSON.stringify(S)===after'),true);assert.equal(g.ev('S.week'),2);assert.equal(g.ev('S.archive[0].rooms.length'),1);assert.equal(g.ev('S.archive[0].result'),'geri çekildi');assert.equal(g.ev('S.archive[0].awardedLoot===Math.round(S.archive[0].loot*0.2)'),true);});
test('Hanedan: real pending raid roundtrip is stable and resolves through reader',()=>{const g=h();g.ev('act("ilerlet");saved=encodeSave(S);resumeSave(parseSave(saved));act("rnext")');assert.equal(g.ev('!!reader'),true);g.ev('while(reader){if(reader.raid.rooms[reader.idx].silent&&!S.prep.silent)act("silent:telsiz");act("rnext");}');assert.equal(g.ev('S.archive.length'),1);assert.equal(g.ev('S.pend'),null);});
test('Hanedan: room choice has bounded consequence and cannot repeat',()=>{const g=h();g.ev('act("ilerlet");while(reader&&!reader.raid.rooms[reader.idx].silent)act("rnext");old=reader.raid.heat;act("silent:telsiz");after=JSON.stringify(S);act("silent:telsiz")');assert.equal(g.ev('JSON.stringify(S)===after'),true);assert.equal(g.ev('reader.raid.heat<=old'),true);});
test('Hanedan: season settlement includes wages, market, contracts and next fixture',()=>{const g=h();g.ev('S.week=16;wage=S.men.filter(m=>m.sozlesme>1).reduce((n,m)=>n+m.yevmiye,0);cash=S.kasa;act("rest")');assert.equal(g.ev('S.season'),2);assert.equal(g.ev('S.week'),1);assert.equal(g.ev('S.kasa===cash-wage+18000+S.sohret*400'),true);assert.equal(g.ev('S.market.length'),6);});
test('Hanedan: jailed crew cannot raid, rest gives a real recovery path',()=>{const g=h();g.ev('S.men.forEach(m=>m.jail=2);act("ilerlet")');assert.equal(g.ev('reader'),null);g.ev('act("rest");act("rest");act("ilerlet")');assert.equal(g.ev('!!reader'),true);});
test('Hanedan: closed life rejects paid controls and preserves save export',()=>{const g=h();g.ev('S.over=true;cash=S.kasa;act("up:depo");act("staff:doktor");act("rest");act("save")');assert.equal(g.ev('S.kasa===cash && S.week===1'),true);assert.ok(g.store.size);});
test('Hanedan: bad nested save and duplicate identities rejected',()=>{const g=h();assert.equal(g.ev('d=JSON.parse(JSON.stringify(S));d.men.push(d.men[0]);migrate(d)'),null);assert.equal(g.ev('d=JSON.parse(JSON.stringify(S));d.market={};migrate(d)'),null);});
test('Hanedan: expired contracts cannot fight until paid once',()=>{const g=h();g.ev('S.men.forEach(m=>m.sozlesme=0);act("ilerlet")');assert.equal(g.ev('reader'),null);g.ev('m=S.men[0];act("soz:pay:"+m.id);c=S.kasa;act("soz:pay:"+m.id)');assert.equal(g.ev('S.kasa===c'),true);});
test('Bükücü: main menu keeps the real save and Continue restores it',()=>{const g=b();g.ev('act("quit")');assert.ok(g.store.size);g.ev('act("cont")');assert.equal(g.ev('view'), 'play');assert.equal(g.ev('S.n'),3);});
test('Bükücü: new game requires explicit replacement decision',()=>{const g=b();g.ev('before=JSON.stringify(S);act("new")');assert.equal(g.ev('JSON.stringify(S)===before'),true);g.ev('act("new-confirm")');assert.equal(g.ev('S'),null);});
test('Bükücü: a built group cannot mortgage its unbuilt property',()=>{const g=b();g.ev('S.own[1]=0;S.own[3]=0;S.bld[1]=1;cash=S.cash[0];act("sen:3")');assert.equal(g.ev('S.sen[3]'),0);assert.equal(g.ev('S.cash[0]===cash'),true);});
test('Bükücü: malformed or negative-cash trade cannot mint money',()=>{const g=b();assert.equal(g.ev('tradeOk({from:0,to:1,give:[],take:[],giveCash:-100,takeCash:0})'),false);g.ev('cash=S.cash.slice();applyTrade({from:0,to:1,give:[],take:[],giveCash:-100,takeCash:0})');assert.deepEqual(json(g,'S.cash'),json(g,'cash'));});
test('Bükücü: dice state survives save/load and terminal actions cannot mutate',()=>{const g=b();g.ev('S.rollPending=[2,3];persist();act("cont")');g.flush();assert.deepEqual(json(g,'S.dice'),[2,3]);g.ev('S.win=0;saved=JSON.stringify(S);act("roll");act("al");act("ode")');assert.equal(g.ev('JSON.stringify(S)===saved'),true);});
test('Bükücü: late callbacks cannot alter replacement game',()=>{const g=b();g.ev('moveBy(0,8,true,function(){afterLand(0)});act("hot3");fresh=JSON.stringify(S)');g.flush();assert.equal(g.ev('JSON.stringify(S)===fresh'),true);});
test('Bükücü: invalid saves rejected rather than booting impossible board',()=>{const g=b();assert.equal(g.ev('d=JSON.parse(JSON.stringify(S));d.own[3]=20;migrate(d)'),null);assert.equal(g.ev('d=JSON.parse(JSON.stringify(S));d.wait="auc";migrate(d)'),null);});
test('Bükücü: stale end-turn cannot skip unresolved purchase or payment',()=>{const g=b();g.ev('S.wait="pay";t=S.turn;act("bitir");act("ok")');assert.equal(g.ev('S.turn===t && S.wait==="pay"'),true);});

test('Hanedan: full squad button and action share the same eligibility',()=>{const g=h();const id=g.ev('S.men.find(m=>!S.prep.squad.includes(m.id)).id');assert.ok(g.ev('blockedAction("squadtog:"+'+JSON.stringify(id)+')'));const before=json(g,'S.prep.squad');g.ev('act("squadtog:"+'+JSON.stringify(id)+')');assert.deepEqual(json(g,'S.prep.squad'),before);});

test("Hanedan: retreat keeps the chosen room consequence in actual awarded loot",()=>{const g=h();g.ev('act("ilerlet");while(reader&&!reader.raid.rooms[reader.idx].silent)act("rnext");cash=reader.raid.rooms[reader.idx].loot;act("silent:kasa");act("rback")');assert.equal(g.ev("S.archive[0].awardedLoot"),Math.round((g.ev("cash")+9000)*0.2));});

test('Bükücü: stale auction clicks cannot bid or fold for the computer',()=>{const g=b();g.ev('act("cpu");S.pos[0]=1;S.wait="buy";act("gec");before=JSON.stringify(S.auc);act("aup");act("aun")');assert.equal(g.ev('JSON.stringify(S.auc)===before'),true);});
test('Bükücü: hotseat trade identifies the real giver and receiver',()=>{const g=b();g.ev('S.turn=1;act("trade")');const walk=n=>[n,...n.children.flatMap(walk)];assert.deepEqual(walk(g.doc.getElementById('sheet')).filter(n=>n.tagName==='H3').map(n=>n.textContent),[g.ev('who(S.trade.from)'),g.ev('who(S.trade.to)')]);});

test('Bükücü: stale trade responses cannot skip payment or reopen a resolved deal',()=>{const g=b();g.ev('act("trade");S.wait="pay";before=JSON.stringify(S);act("tno");act("tyes");act("toffer")');assert.equal(g.ev('JSON.stringify(S)===before'),true);g.ev('S.wait="roll";act("tno");before=JSON.stringify(S);act("tno");act("tyes")');assert.equal(g.ev('JSON.stringify(S)===before'),true);});
